### ISSUE TITLE
post-link failed for: conda-forge::widgetsnbextension-3.0.8-py36_0

### ISSUE THREAD

**Issue by sebastienaubry** [conda-forge/widgetsnbextension-feedstock#33] opened 2017-11-20 12:22 UTC
Hi,
I experience the problem summarized below, reproducible on a new environment:
```
$ conda create -n python3 python=3 jupyter
Fetching package metadata ...............
Solving package specifications: ..........

Package plan for installation in environment /path/to/miniconda/envs/python3:

The following NEW packages will be INSTALLED:

    bleach:             2.0.0-py36_0       conda-forge
    ca-certificates:    2017.11.5-0        conda-forge
    certifi:            2017.11.5-py36_0   conda-forge
[...]
    jupyter:            1.0.0-py36_0       conda-forge
    jupyter_client:     5.1.0-py36_0       conda-forge
    jupyter_console:    5.2.0-py36_0       conda-forge
    jupyter_core:       4.4.0-py_0         conda-forge
[...]
    python:             3.6.3-1            conda-forge
[...]
    widgetsnbextension: 3.0.8-py36_0       conda-forge
[...]

Proceed ([y]/n)? y

Linking packages ...
Error: Error: post-link failed for: conda-forge::widgetsnbextension-3.0.8-py36_0#########################    |  96%
```

Thanks

**Comment by jakirkham** [comment] 2018-01-30 01:06
Thanks for the report. Closing as a duplicate of issue ( https://github.com/conda-forge/widgetsnbextension-feedstock/issues/18 ).

**Closed by jakirkham** 2018-01-30 01:06 UTC
