### ISSUE TITLE
LinkError with widgetsnbextension

### ISSUE THREAD

**Issue by dkoppstein** [conda-forge/widgetsnbextension-feedstock#18] opened 2017-01-24 22:38 UTC
Hi, I've been getting an error with this build.

Am running on Ubuntu 14.04 with conda 4.3.7. 

My conda-requirements.txt file was created using `conda list --explicit` and contains the line

`https://conda.anaconda.org/conda-forge/linux-64/widgetsnbextension-1.2.6-py34_3.tar.bz2`

Creating a new environment gives me: 

```
ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'conda-forge::widgetsnbextension-1.2.6-py34_3'.
LinkError: Link error: Error: post-link failed for: conda-forge::widgetsnbextension-1.2.6-py34_3

Attempting to roll back.



LinkError: Link error: Error: post-link failed for: conda-forge::widgetsnbextension-1.2.6-py34_3
```

Rolling back to conda 4.0.5 allowed the environment to be created successfully, but [I was advised](https://github.com/conda/conda/issues/4374) that 

>Conda 4.0 continued with certain failure conditions, even though it's unsafe to do so. When unspecified failures occur in conda 4.3, such as something with a post-link script, we roll back to the previous state so that we don't mess up your environment in unpredictable ways.

thus, there might still be an issue with this recipe.

**Comment by jakirkham** [comment] 2017-01-25 01:30
Thanks for the bug report. Could you please include `conda info` and `conda list` for the relevant environment?

FYI we are dropping support for Python 3.4 throughout conda-forge. Is there some reason you are still using it instead of 3.5 or possibly 3.6?

**Comment by dkoppstein** [comment] 2017-01-25 02:10
Some packages still depend on python=3.4. Hopefully they will be
incremented soon.

**Comment by jakirkham** [comment] 2017-01-25 03:51
In conda-forge or in general?

**Comment by CJ-Wright** [comment] 2017-07-20 00:32
I also got this message during an update to py36
```WARNING conda.core.link:run_script(519): pre-unlink script failed for package conda-forge::widgetsnbextension-2.0.0-py35_0
consider notifying the package maintainer```

```
dp_dev3) christopher@christopher-ubuntu ~ $ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 2.1.17
         python version : 3.5.3.final.0
       requests version : 2.18.1
       root environment : /home/christopher/mc  (writable)
    default environment : /home/christopher/mc/envs/dp_dev3
       envs directories : /home/christopher/mc/envs
                          /home/christopher/.conda/envs
          package cache : /home/christopher/mc/pkgs
                          /home/christopher/.conda/pkgs
           channel URLs : http://conda.anaconda.org/diffpy/linux-64
                          http://conda.anaconda.org/diffpy/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/lightsource2-tag/linux-64
                          https://conda.anaconda.org/lightsource2-tag/noarch
                          https://conda.anaconda.org/soft-matter/linux-64
                          https://conda.anaconda.org/soft-matter/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/diffpy/linux-64
                          https://conda.anaconda.org/diffpy/noarch
            config file : /home/christopher/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.18.1 CPython/3.5.3 Linux/4.4.0-83-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000
```

```accelerate                2.3.1               np111py36_0  
accelerate_cudalib        2.0                           0  
amostra                   0.2              py36h2c6fa9f_0    lightsource2-tag
asn1crypto                0.22.0                   py36_0    conda-forge
attrs                     17.2.0                   py36_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                    py36_1    conda-forge
bkcharts                  0.2                      py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                    py36_0    conda-forge
bokeh                     0.12.6                   py36_0    conda-forge
boltons                   17.1.0                   py36_0    conda-forge
boto3                     1.4.4                    py36_0    conda-forge
botocore                  1.5.84                   py36_0    conda-forge
ca-certificates           2017.4.17                     0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2017.4.17                py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.2                    py36_1    conda-forge
click                     6.7                      py36_0    conda-forge
cloog                     0.18.0                        0  
cloudpickle               0.3.1                    py36_0    conda-forge
cryptography              1.9                      py36_0    conda-forge
cudatoolkit               7.5                           0  
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.25.2                   py36_1    conda-forge
cytoolz                   0.8.2                    py36_0    conda-forge
dask                      0.15.1                   py36_0    conda-forge
databroker                0.8.4            py36hce1fc5c_0    lightsource2-tag
dbus                      1.10.10                       3    conda-forge
decorator                 4.1.1                    py36_0    conda-forge
distributed               1.18.0                   py36_0    conda-forge
doct                      1.0.3            py36h4a913d2_0    lightsource2-tag
docutils                  0.13.1                   py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
epics-base                3.14.12.6            h6af44bd_2    lightsource2-tag
et_xmlfile                1.0.1                    py36_0    conda-forge
event-model               1.2.0            py36hfe52871_1    lightsource2-tag
expat                     2.2.1                         0    conda-forge
filestore                 0.8.0            py36hfeddc44_0    lightsource2-tag
flake8                    3.3.0                    py36_0    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
gcc                       4.8.5                         7  
gettext                   0.19.7                        1    conda-forge
glib                      2.51.4                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
graphite2                 1.3.9                         0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
h5py                      2.7.0               np111py36_1    conda-forge
harfbuzz                  1.4.3                         0    conda-forge
hdf5                      1.8.18                        0    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
html5lib                  0.9999999                py36_0    conda-forge
humanize                  0.5.1                    py36_0    conda-forge
hypothesis                3.11.6                   py36_0    conda-forge
icu                       58.1                          1    conda-forge
idna                      2.5                      py36_0    conda-forge
imageio                   2.2.0                    py36_0    conda-forge
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.1.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                6.0.0                    py36_0    conda-forge
isl                       0.12.2                        0  
jdcal                     1.3                      py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.5                    py36_0    conda-forge
jmespath                  0.9.3                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
jsonschema                2.5.1                    py36_0    conda-forge
jupyter                   1.0.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_console           5.1.0                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libsodium                 1.0.10                        0    conda-forge
libtiff                   4.0.6                         7    conda-forge
libuuid                   1.0.3                         1    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         4    conda-forge
llvmlite                  0.15.0                   py36_0  
lmfit                     0.9.7                    py36_0    conda-forge
locket                    0.2.0                    py36_1    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.0.2               np111py36_0    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
metadatastore             0.7.0            py36he1d0001_0    lightsource2-tag
mistune                   0.7.4                    py36_0    conda-forge
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py36_3  
mongoquery                1.1.0                    py36_0    conda-forge
mpc                       1.0.3                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpi4py                    2.0.0                    py36_2    conda-forge
mpich                     3.2                           4    conda-forge
mpich2                    1.4.1p1                       0  
msgpack-python            0.4.8                    py36_0    conda-forge
nbconvert                 5.2.1                    py36_1    conda-forge
nbformat                  4.3.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py36_0    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.0.0                    py36_0    conda-forge
numba                     0.30.1              np111py36_0  
numpy                     1.11.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
olefile                   0.44                     py36_0    conda-forge
openblas                  0.2.19                        2    conda-forge
openpyxl                  2.5.0a2                  py36_0    conda-forge
openssl                   1.0.2l                        0    conda-forge
ophyd                     0.6.1            py36hd6b8f76_0    lightsource2-tag
pandas                    0.20.3                   py36_1    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
pango                     1.40.4                        0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.3                    py36_0    conda-forge
pillow                    4.2.1                    py36_0    conda-forge
pims                      0.4                      py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pixman                    0.34.0                        0    conda-forge
prettytable               0.7.2                    py36_1    conda-forge
prompt_toolkit            1.0.14                   py36_0    conda-forge
psutil                    5.2.1                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.4.34                   py36_0    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyepics                   3.2.6            py36hbe2c63c_1    lightsource2-tag
pyflakes                  1.5.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pymongo                   3.2.2            py36he9b4339_0    lightsource2-tag
pympler                   0.5                      py36_0    conda-forge
pyopenssl                 16.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
pytest                    3.1.3                    py36_0    conda-forge
python                    3.6.1                         3    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pywavelets                0.5.2               np111py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                         3    conda-forge
qtconsole                 4.3.0                    py36_0    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.1                   py36_0    conda-forge
s3fs                      0.1.1                    py36_0    conda-forge
s3transfer                0.1.10                   py36_1    conda-forge
scikit-image              0.13.0              np111py36_0    conda-forge
scipy                     0.19.1          np111py36_blas_openblas_200  [blas_openblas]  conda-forge
setuptools                33.1.1                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
slicerator                0.9.8                    py36_0    conda-forge
snakeviz                  0.4.1                    py36_0  
sortedcontainers          1.5.3                    py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
super_state_machine       1.0              py36hd006471_0    lightsource2-tag
tblib                     1.3.2                    py36_0    conda-forge
terminado                 0.6                      py36_0    conda-forge
testpath                  0.3                      py36_0    conda-forge
tifffile                  0.12.1              np111py36_0    conda-forge
tk                        8.5.19                        1    conda-forge
toolz                     0.8.2                    py36_0    conda-forge
tornado                   4.5.1                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
tzlocal                   1.4                      py36_0    conda-forge
ujson                     1.35                     py36_0  
urllib3                   1.21.1                   py36_1    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
widgetsnbextension        2.0.0                    py36_0    conda-forge
xlsxwriter                0.9.6                    py36_0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xray-vision               0.0.7            py36h8e02a93_0    lightsource2-tag
xraylib                   3.2.0               np111py36_2    conda-forge
xz                        5.2.2                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zeromq                    4.2.1                         1    conda-forge
zict                      0.1.2                    py36_0    conda-forge
zlib                      1.2.11                        0    conda-forge
zope                      1.0                      py36_0  
zope.interface            4.4.2                    py36_0```

**Comment by kiwifb** [comment] 2018-01-29 23:50
And I get it with a fresh install on py35 and ubuntu 16.04
```
Current conda install:

               platform : linux-64
          conda version : 4.3.33
       conda is private : False
      conda-env version : 4.3.33
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.18.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
                          /root/.conda/envs
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /opt/conda/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.33 requests/2.18.4 CPython/3.5.2 Linux/4.4.0-112-generic debian/stretch/sid glibc/2.23    
                UID:GID : 0:0
```

```
# packages in environment at /opt/conda:
#
asn1crypto                0.22.0                   py35_0    conda-forge
certifi                   2017.11.5                py35_0    conda-forge
cffi                      1.11.2                   py35_0    conda-forge
chardet                   3.0.4                    py35_0    conda-forge
conda                     4.3.33                   py35_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
cryptography              2.1.4                    py35_0    conda-forge
decorator                 4.1.2                    py35_0    conda-forge
entrypoints               0.2.3                    py35_1    conda-forge
gmp                       6.1.2                         0    conda-forge
idna                      2.6                      py35_1    conda-forge
ipykernel                 4.7.0                    py35_0    conda-forge
ipyparallel               6.0.2                    py35_0    conda-forge
ipython                   6.2.1                    py35_1    conda-forge
ipython_genutils          0.2.0                    py35_0    conda-forge
jedi                      0.11.1                   py35_0    conda-forge
jinja2                    2.10                     py35_0    conda-forge
jsonschema                2.6.0                    py35_0    conda-forge
jupyter_client            5.2.2                    py35_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libsodium                 1.0.15                        1    conda-forge
markupsafe                1.0                      py35_0    conda-forge
mistune                   0.8.3                      py_0    conda-forge
nbconvert                 4.2.0                    py35_0    conda-forge
nbformat                  4.4.0                    py35_0    conda-forge
notebook                  5.3.1                    py35_1    conda-forge
openssl                   1.0.2j                        0    defaults
pandoc                    2.1.1                         0    conda-forge
parso                     0.1.1                      py_0    conda-forge
pexpect                   4.3.1                    py35_0    conda-forge
pickleshare               0.7.4                    py35_0    conda-forge
pip                       8.1.2                    py35_0    defaults
prompt_toolkit            1.0.15                   py35_0    conda-forge
ptyprocess                0.5.2                    py35_0    conda-forge
pycosat                   0.6.1                    py35_1    defaults
pycparser                 2.18                     py35_0    conda-forge
pycrypto                  2.6.1                    py35_4    defaults
pygments                  2.2.0                    py35_0    conda-forge
pyopenssl                 17.4.0                   py35_0    conda-forge
pysocks                   1.6.8                    py35_1    conda-forge
python                    3.5.2                         0    defaults
python-dateutil           2.6.1                    py35_0    conda-forge
pyzmq                     16.0.2                   py35_3    conda-forge
readline                  6.2                           2    defaults
requests                  2.18.4                   py35_1    conda-forge
ruamel_yaml               0.11.14                  py35_0    defaults
send2trash                1.4.2                      py_0    conda-forge
setuptools                27.2.0                   py35_0    defaults
simplegeneric             0.8.1                    py35_0    conda-forge
six                       1.11.0                   py35_1    conda-forge
sqlite                    3.13.0                        0    defaults
terminado                 0.8.1                    py35_0    conda-forge
tk                        8.5.18                        0    defaults
tornado                   4.5.3                    py35_0    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
urllib3                   1.22                     py35_0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
wheel                     0.29.0                   py35_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.2.1                         1    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by jakirkham** [comment] 2018-01-30 00:25
Sorry doing what @kiwifb? Could you please include steps to reproduce?

**Comment by kiwifb** [comment] 2018-01-30 00:31
Sorry it failed while I was installing from an ansible playbook but I could reproduce it on the command line with `conda install widgetsnbextension`.

**Comment by jakirkham** [comment] 2018-01-30 01:10
This *may* be solved with `conda` 4.4. Could you please test?

**Comment by kiwifb** [comment] 2018-01-30 01:28
I am actually using miniconda which doesn't seem to have a 4.4 version yet. That means I would need to go full anaconda first.

**Comment by jakirkham** [comment] 2018-01-30 01:34
It should be possible to get it by running `conda install -c defaults conda=4.4`.

**Comment by isuruf** [comment] 2018-01-30 01:37
> I see that jupyter_core is marked py_0 in my list and it is installed in a different (/opt/conda/site-packages instead of /opt/conda/lib/python3.5/site-packages) path. However when I start conda's python3.5 that python-version independent path is not in any path that python knows about.

Did you install `jupyter_core` when `conda<4.3`? Can you try removing `jupyter_core` and installing it again?

**Comment by kiwifb** [comment] 2018-01-30 01:39
Hi @isuruf , could have. I don't think it happened but it's a possibility since I am working with a rather complicated ansible recipe that I haven't completely unravelled.

But right now I am moving to 4.4 and updating what's already there. If it fails, that's next.

**Comment by kiwifb** [comment] 2018-01-30 01:51
Top hit for jupyter_core currently insist on being in the slot py_0. I would have to force one of the bizarre slots of the default channel.
```
 conda search jupyter_core
Fetching package metadata .............
jupyter_core                 4.0.2                    py27_0  defaults        
                             4.0.2                    py34_0  defaults        
                             4.0.3                    py27_0  defaults        
                             4.0.3                    py34_0  defaults        
                             4.0.4                    py27_0  defaults        
                             4.0.4                    py34_0  defaults        
                             4.0.4                    py35_0  defaults        
                             4.0.6                    py27_0  defaults        
                             4.0.6                    py34_0  defaults        
                             4.0.6                    py35_0  defaults        
                             4.1.0                    py27_0  defaults        
                             4.1.0                    py34_0  defaults        
                             4.1.0                    py35_0  defaults        
                             4.1.1                    py27_0  defaults        
                             4.1.1                    py34_0  defaults        
                             4.1.1                    py35_0  defaults        
                             4.2.0                    py27_0  defaults        
                             4.2.0                    py34_0  defaults        
                             4.2.0                    py35_0  defaults        
                             4.2.1                    py27_0  defaults        
                             4.2.1                    py34_0  defaults        
                             4.2.1                    py35_0  defaults        
                             4.2.1                    py36_0  defaults        
                             4.3.0                    py27_0  defaults        
                             4.3.0                    py35_0  defaults        
                             4.3.0                    py36_0  defaults        
                             4.3.0            py27hcd9ae3a_0  defaults        
                             4.3.0            py35he2f7985_0  defaults        
                             4.3.0            py36h357a921_0  defaults        
                             4.4.0            py27h345911c_0  defaults        
                             4.4.0            py35ha89e94b_0  defaults        
                             4.4.0            py36h7c827e3_0  defaults        
                             4.1.0                    py27_0  conda-forge     
                             4.1.0                    py34_0  conda-forge     
                             4.1.0                    py35_0  conda-forge     
                             4.1.1                    py27_0  conda-forge     
                             4.1.1                    py34_0  conda-forge     
                             4.1.1                    py35_0  conda-forge     
                             4.1.1                    py27_1  conda-forge     
                             4.1.1                    py34_1  conda-forge     
                             4.1.1                    py35_1  conda-forge     
                             4.2.0                    py27_0  conda-forge     
                             4.2.0                    py34_0  conda-forge     
                             4.2.0                    py35_0  conda-forge     
                             4.2.1                    py27_0  conda-forge     
                             4.2.1                    py34_0  conda-forge     
                             4.2.1                    py35_0  conda-forge     
                             4.2.1                    py36_0  conda-forge     
                             4.3.0                    py27_0  conda-forge     
                             4.3.0                    py35_0  conda-forge     
                             4.3.0                    py36_0  conda-forge     
                             4.4.0                      py_0  conda-forge 
```

**Comment by jakirkham** [comment] 2018-01-30 01:52
What's wrong with using the `py_0` one?

**Comment by isuruf** [comment] 2018-01-30 01:54
`py_0` is a noarch python build which needs conda>=4.3. If the package was installed when conda <4.2, the installation will break. So, try uninstalling `jupyter_core` and install it again and check if it is installed in `/opt/conda/lib/python3.5/site-packages`

**Comment by kiwifb** [comment] 2018-01-30 02:01
Yep it must have been installed with conda<4.3. Everything works now. The ansible recipe starts with conda-4.2.12, I have no idea when the conda update is triggered. The upgrade must have been a side effect of another command. 

I will update that recipe to a more recent conda. I wouldn't be shocked if `jupyter_core` not being found is the root cause of all the reported instance of this issue.

**Comment by jasongrout** [comment] 2018-01-30 07:18
> I will update that recipe to a more recent conda. I wouldn't be shocked if jupyter_core not being found is the root cause of all the reported instance of this issue.

I think you're right. I've seen the root error message "LinkError: Link error: Error: post-link failed for: ...widgetsnbextension..." happen because the noarch jupyter_core package was installed using conda <4.3. Basically, IIRC, there's an error running `jupyter nbextension`. This is because the jupyter_core commands do not get installed correctly because conda <4.3 doesn't understand the noarch package format. Upgrading conda fixes all of this.

**Closed** 2018-01-30 07:18 UTC
