### ISSUE TITLE
v2.0.0 pre-unlink script fails

### ISSUE THREAD

**Issue by willfurnass** [conda-forge/widgetsnbextension-feedstock#21] opened 2017-03-10 14:53 UTC
When I try to `conda env remove` an environment containing `widgetsnbextension` I get:

```
WARNING conda.core.link:run_script(512): pre-unlink script failed for package conda-forge::widgetsnbextension-2.0.0-py35_0
```

**Comment by msolbrig** [comment] 2017-03-31 01:54
I have also hit the same issue, widgetsnbextension-1.2.6-py27_3

**Comment by jeffreywolf** [comment] 2017-05-23 18:21
I had a similar issue.  This was the terminal output.
```
WARNING conda.core.link:run_script(519): pre-unlink script failed for package conda-forge::widgetsnbextension-2.0.0-py36_0
consider notifying the package maintainer
```

**Comment by jakirkham** [comment] 2017-05-23 18:34
What if you just try removing `widgetsnbextension` first and then the environment? FWIW I expect removing the environment would result in unexpected behavior w.r.t. post-(un)link scripts.

**Comment by jeffreywolf** [comment] 2017-05-24 15:14
Here is a minimal example the causes the problem. Since jupyter is widely used I figure this is a good real world case.  I hit y to proceed whenever prompted.

```
$ conda create -c conda-forge -n testenv jupyter
...
$ conda env remove -n testenv
...
WARNING conda.core.link:run_script(517): pre-unlink script failed for package conda-forge::widgetsnbextension-2.0.0-py36_0
consider notifying the package maintainer
```

If you remove the package before removing the environment you don't get the warning. In this case, you also remove jupyter since it depends on widgetsnbextension. 

```
$ conda create -c conda-forge -n testenv jupyter
...
$ conda remove -n testenv widgetsnbextension
...
$ conda env remove -n testenv
...
```

**Comment by jakirkham** [comment] 2017-05-24 17:21
Thanks for the follow-up. That's basically what I expected.

FWICT this is a `conda` bug (or enhancement). Essentially it doesn't appear that `conda` is respecting topological order when clearing environments. Have described this in issue ( https://github.com/conda/conda/issues/5417 ).

That said, when conda removes an environment it should also clean up all the files that `pre-unlink` would have gotten rid of as they are in that environment. So this warning shouldn't indicate a reall problem in this case (though it is admittedly not nice).

As for this package, we could probably skip the problematic step if we can't run `jupyter-nbextension`, which would silence the warning. Though I think this might be more dangerous than this warning as it would mask actual uninstall issues as well.

**Comment by jrovegno** [comment] 2017-06-03 19:49
When i try to `conda update --all` in my root environment  containing widgetsnbextension I get:
```
WARNING conda.core.link:run_script(519): pre-unlink script failed for package conda-forge::widgetsnbextension-2.0.0-py27_0
consider notifying the package maintainer
```
Nothing happened for a while, so I press Control+C, now the command conda is broken.
When i try to `conda info`  I get:
```
Traceback (most recent call last):
  File "C:\Users\MyUser\Anaconda\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 584
....
```
I have to restart the terminal and now conda works, but when I run `jupyter notebook` and open some nb the kernel die unexpected.

**Comment by AnalogArsonist** [comment] 2017-06-22 01:22
@jrovegno I just ran the same exact command and got the same error, but I let the install finish. It sat at the warning for about 5 minutes, maybe longer before dumping me back into the prompt. The install seemed to work as I don't get any errors and jupyter works fine. Maybe try update all again without cancelling. I also read to try running 'conda update traitlets' prior to the update all.

**Comment by ijstokes** [comment] 2017-07-18 17:16
I have latest conda (v4.3.22), and I am still getting this error, though not if I try re-installing with a "force" install.  See trace below.

```
widgetsnbexten 100% |#############################################################| Time: 0:00:00   3.49 MB/s
ipywidgets-6.0 100% |#############################################################| Time: 0:00:00   2.61 MB/s
WARNING conda.core.link:run_script(519): pre-unlink script failed for package conda-forge::widgetsnbextension-2.0.0-py36_0
consider notifying the package maintainer
(myenv) twitter $ conda install -f -c conda-forge widgetsnbextension
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/ijstokes/anaconda/envs/myenv:

The following packages will be SUPERSEDED by a higher-priority channel:

    widgetsnbextension: 2.0.0-py36_0 --> 2.0.0-py36_0 conda-forge

Proceed ([y]/n)? y

widgetsnbexten 100% |#############################################################| Time: 0:00:01 477.43 kB/s
(myenv) twitter $ 
```

**Comment by jakirkham** [comment] 2017-07-18 17:21
As noted before, this is an open issue for `conda`. ( https://github.com/conda/conda/issues/5417 ) Though `conda-build` would need to expose some syntax for us to fix the problem at the recipe level as well.

**Comment by blink1073** [comment] 2017-10-05 15:25
We could skirt the issue by first checking for the existence of `jupyter-nbextension` in the unlink scripts.

**Comment by jasongrout** [comment] 2017-10-05 15:28
Great idea for a workaround - thanks!

**Comment by blink1073** [comment] 2017-10-05 15:49
cf https://github.com/conda-forge/jupyterlab-feedstock/pull/67/files

**Comment by jakirkham** [comment] 2017-10-05 16:22
We need the check in `widgetsnbextension` though, right? Also shouldn't we warn in this case as the uninstall is incomplete (unless the whole environment is removed)?

**Comment by blink1073** [comment] 2017-10-05 16:24
Yes, I had pointed to that PR as an example. The issue only arises in practice when removing the environment, and the warning is confusing to users.

**Comment by blink1073** [comment] 2017-10-05 16:26
If `jupyter-nbextension` doesn't exist, then modifying a config file that may or may not be there is not enough reason to show a warning.

**Comment by damianavila** [comment] 2017-10-06 14:47
> Great idea for a workaround - thanks!

Yep, nice one :+1:

**Comment by jakirkham** [comment] 2018-04-19 03:32
So this should be solved in newer versions of conda, 4.4+. Currently conda-forge packages the latest of the 4.5+ line, which also have this fix.

**Comment by jasongrout** [comment] 2018-04-19 04:48
Thanks for following up on this!

**Comment by jasongrout** [comment] 2018-04-19 04:48
I guess we'll close this as (eventually) fixed in conda.

**Closed by jasongrout** 2018-04-19 04:48 UTC

**Comment by jakirkham** [comment] 2018-04-19 05:39
Sure.

TBH it was always a `conda` issue. So it's reasonable it got fixed there and the fix they made was quite nice not just for this case, but a variety of cases. Namely it does a topo sort before performing removal of packages.

There are probably a bunch of similar issues on Jupyter related feedstocks that we can close. Basically anything (fairly) complaining about pre-unlink steps not working properly should be solved with a newer `conda`.
